services:
  postgres:
    image: postgres:15
    container_name: recipeDB-postgres
    restart: always
    environment:
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_pass
      POSTGRES_DB: recipe_db

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
